version: "3"

services:
  app:
    container_name: "infra-hello-flask"
    image: infra_util_microservice-app:latest
    ports:
      - 5000:5000
    networks:
      - infra_util_net
networks:
  infra_util_net:
